// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dgut-icourse/ent/course"
	"dgut-icourse/ent/object"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Course is the model entity for the Course schema.
type Course struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 创建时间
	CreatedAt int64 `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// 课程ID
	CourseID string `json:"courseID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CourseQuery when eager-loading is set.
	Edges                CourseEdges `json:"edges"`
	object_course        *uuid.UUID
	object_teach_courses *uuid.UUID
	object_setup_courses *uuid.UUID
	selectValues         sql.SelectValues
}

// CourseEdges holds the relations/edges for other nodes in the graph.
type CourseEdges struct {
	// Object holds the value of the object edge.
	Object *Object `json:"object,omitempty"`
	// 授课教师
	Teacher *Object `json:"teacher,omitempty"`
	// 开课单位
	Organization *Object `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ObjectOrErr returns the Object value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseEdges) ObjectOrErr() (*Object, error) {
	if e.Object != nil {
		return e.Object, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: object.Label}
	}
	return nil, &NotLoadedError{edge: "object"}
}

// TeacherOrErr returns the Teacher value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseEdges) TeacherOrErr() (*Object, error) {
	if e.Teacher != nil {
		return e.Teacher, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: object.Label}
	}
	return nil, &NotLoadedError{edge: "teacher"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CourseEdges) OrganizationOrErr() (*Object, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: object.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Course) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case course.FieldID, course.FieldCreatedAt, course.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case course.FieldCourseID:
			values[i] = new(sql.NullString)
		case course.ForeignKeys[0]: // object_course
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case course.ForeignKeys[1]: // object_teach_courses
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case course.ForeignKeys[2]: // object_setup_courses
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Course fields.
func (c *Course) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case course.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case course.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Int64
			}
		case course.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Int64
			}
		case course.FieldCourseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field courseID", values[i])
			} else if value.Valid {
				c.CourseID = value.String
			}
		case course.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field object_course", values[i])
			} else if value.Valid {
				c.object_course = new(uuid.UUID)
				*c.object_course = *value.S.(*uuid.UUID)
			}
		case course.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field object_teach_courses", values[i])
			} else if value.Valid {
				c.object_teach_courses = new(uuid.UUID)
				*c.object_teach_courses = *value.S.(*uuid.UUID)
			}
		case course.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field object_setup_courses", values[i])
			} else if value.Valid {
				c.object_setup_courses = new(uuid.UUID)
				*c.object_setup_courses = *value.S.(*uuid.UUID)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Course.
// This includes values selected through modifiers, order, etc.
func (c *Course) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryObject queries the "object" edge of the Course entity.
func (c *Course) QueryObject() *ObjectQuery {
	return NewCourseClient(c.config).QueryObject(c)
}

// QueryTeacher queries the "teacher" edge of the Course entity.
func (c *Course) QueryTeacher() *ObjectQuery {
	return NewCourseClient(c.config).QueryTeacher(c)
}

// QueryOrganization queries the "organization" edge of the Course entity.
func (c *Course) QueryOrganization() *ObjectQuery {
	return NewCourseClient(c.config).QueryOrganization(c)
}

// Update returns a builder for updating this Course.
// Note that you need to call Course.Unwrap() before calling this method if this Course
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Course) Update() *CourseUpdateOne {
	return NewCourseClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Course entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Course) Unwrap() *Course {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Course is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Course) String() string {
	var builder strings.Builder
	builder.WriteString("Course(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", c.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", c.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("courseID=")
	builder.WriteString(c.CourseID)
	builder.WriteByte(')')
	return builder.String()
}

// Courses is a parsable slice of Course.
type Courses []*Course
