// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dgut-icourse/ent/comment"
	"dgut-icourse/ent/course"
	"dgut-icourse/ent/object"
	"dgut-icourse/ent/organization"
	"dgut-icourse/ent/schema"
	"dgut-icourse/ent/user"
	"dgut-icourse/ent/userinfo"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() int64)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() int64)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() int64)
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[1].Descriptor()
	// comment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	comment.ContentValidator = commentDescContent.Validators[0].(func(string) error)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	courseMixin := schema.Course{}.Mixin()
	courseMixinFields0 := courseMixin[0].Fields()
	_ = courseMixinFields0
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescCreatedAt is the schema descriptor for created_at field.
	courseDescCreatedAt := courseMixinFields0[0].Descriptor()
	// course.DefaultCreatedAt holds the default value on creation for the created_at field.
	course.DefaultCreatedAt = courseDescCreatedAt.Default.(func() int64)
	// courseDescUpdatedAt is the schema descriptor for updated_at field.
	courseDescUpdatedAt := courseMixinFields0[1].Descriptor()
	// course.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	course.DefaultUpdatedAt = courseDescUpdatedAt.Default.(func() int64)
	// course.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	course.UpdateDefaultUpdatedAt = courseDescUpdatedAt.UpdateDefault.(func() int64)
	objectMixin := schema.Object{}.Mixin()
	objectMixinFields0 := objectMixin[0].Fields()
	_ = objectMixinFields0
	objectFields := schema.Object{}.Fields()
	_ = objectFields
	// objectDescCreatedAt is the schema descriptor for created_at field.
	objectDescCreatedAt := objectMixinFields0[0].Descriptor()
	// object.DefaultCreatedAt holds the default value on creation for the created_at field.
	object.DefaultCreatedAt = objectDescCreatedAt.Default.(func() int64)
	// objectDescUpdatedAt is the schema descriptor for updated_at field.
	objectDescUpdatedAt := objectMixinFields0[1].Descriptor()
	// object.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	object.DefaultUpdatedAt = objectDescUpdatedAt.Default.(func() int64)
	// object.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	object.UpdateDefaultUpdatedAt = objectDescUpdatedAt.UpdateDefault.(func() int64)
	// objectDescName is the schema descriptor for name field.
	objectDescName := objectFields[1].Descriptor()
	// object.NameValidator is a validator for the "name" field. It is called by the builders before save.
	object.NameValidator = objectDescName.Validators[0].(func(string) error)
	// objectDescDesc is the schema descriptor for desc field.
	objectDescDesc := objectFields[2].Descriptor()
	// object.DescValidator is a validator for the "desc" field. It is called by the builders before save.
	object.DescValidator = objectDescDesc.Validators[0].(func(string) error)
	// objectDescID is the schema descriptor for id field.
	objectDescID := objectFields[0].Descriptor()
	// object.DefaultID holds the default value on creation for the id field.
	object.DefaultID = objectDescID.Default.(func() uuid.UUID)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() int64)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() int64)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() int64)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() int64)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() int64)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() int64)
	// userDescNickName is the schema descriptor for nickName field.
	userDescNickName := userFields[1].Descriptor()
	// user.NickNameValidator is a validator for the "nickName" field. It is called by the builders before save.
	user.NickNameValidator = userDescNickName.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[3].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = func() func(string) error {
		validators := userDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescOpenid is the schema descriptor for openid field.
	userDescOpenid := userFields[5].Descriptor()
	// user.OpenidValidator is a validator for the "openid" field. It is called by the builders before save.
	user.OpenidValidator = userDescOpenid.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userinfoMixin := schema.UserInfo{}.Mixin()
	userinfoMixinFields0 := userinfoMixin[0].Fields()
	_ = userinfoMixinFields0
	userinfoFields := schema.UserInfo{}.Fields()
	_ = userinfoFields
	// userinfoDescCreatedAt is the schema descriptor for created_at field.
	userinfoDescCreatedAt := userinfoMixinFields0[0].Descriptor()
	// userinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	userinfo.DefaultCreatedAt = userinfoDescCreatedAt.Default.(func() int64)
	// userinfoDescUpdatedAt is the schema descriptor for updated_at field.
	userinfoDescUpdatedAt := userinfoMixinFields0[1].Descriptor()
	// userinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userinfo.DefaultUpdatedAt = userinfoDescUpdatedAt.Default.(func() int64)
	// userinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userinfo.UpdateDefaultUpdatedAt = userinfoDescUpdatedAt.UpdateDefault.(func() int64)
}
