// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseComment is the predicate function for coursecomment builders.
type CourseComment func(*sql.Selector)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Other is the predicate function for other builders.
type Other func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserInfo is the predicate function for userinfo builders.
type UserInfo func(*sql.Selector)
